'use client';
import {useState} from 'react';
import {Activity, BellRing, CheckCircle2, Radio, Siren} from 'lucide-react';
import {useLedger} from '@/lib/ledger';
import deployment from '@/artifacts/deployment.json';

export default function Home(){
 const l=useLedger(deployment.address); const [id,setId]=useState('INCIDENT-001'); const [service,setService]=useState('Payments API'); const [summary,setSummary]=useState('Intermittent failures are affecting a subset of requests.'); const [status,setStatus]=useState('https://status.example.com/'); const [postmortem,setPostmortem]=useState('https://postmortem.example.com/'); const [advisory,setAdvisory]=useState('https://advisory.example.com/'); const [record,setRecord]=useState<any>(null);
 async function open(){await l.write('open_incident',[id,service,summary,status,postmortem,advisory],async()=>true)}
 async function verify(){const iid=id.trim().toUpperCase();await l.write('verify_incident',[iid],async()=>{const r=await l.read('get_incident',[l.account,iid]);setRecord(r);return r?.state==='VERIFIED'})}
 return <main><header><div className="brand"><Activity/><span>CIVIC<span>SIGNAL</span></span></div><div className="tag">PUBLIC INCIDENT INTELLIGENCE / STUDIONET</div><button className="connect" onClick={l.connect}>{l.account?l.account.slice(0,6)+'…'+l.account.slice(-4):'Connect wallet'}</button></header><section className="hero"><div><p className="kicker">A THREE-WAY STATUS CHECK</p><h1>When the signal<br/><i>changes, know.</i></h1><p>CivicSignal turns an incident into an auditable timeline. Validators refetch the status page, postmortem, and independent advisory before classifying what is really happening.</p></div><div className="radar"><Radio/><strong>LIVE CHECK</strong><small>3 independent hosts<br/>conflict-aware verdicts</small></div></section><section className="console"><div className="form"><span>01 / INCIDENT INTAKE</span><h2>Open a signal</h2><label>Incident ID<input value={id} onChange={e=>setId(e.target.value)}/></label><label>Service<input value={service} onChange={e=>setService(e.target.value)}/></label><label>What happened<textarea value={summary} onChange={e=>setSummary(e.target.value)}/></label></div><div className="sources"><h3><Siren/> Source relay</h3><label>STATUS PAGE<input value={status} onChange={e=>setStatus(e.target.value)}/></label><label>POSTMORTEM<input value={postmortem} onChange={e=>setPostmortem(e.target.value)}/></label><label>ADVISORY<input value={advisory} onChange={e=>setAdvisory(e.target.value)}/></label><div className="actions"><button onClick={open} disabled={!l.account||l.busy}>Open incident ↗</button><button onClick={verify} disabled={!l.account||l.busy}>Verify signal <BellRing size={16}/></button></div><p className="status">{l.message||'Connect your wallet to publish the incident timeline.'}</p></div></section>{record&&<section className="signal"><div className="signal-title"><CheckCircle2/><div><span>LATEST SIGNAL</span><h2>{record.signal}</h2></div></div><p>{record.finding}</p><small>NEXT STEP · {record.next_step}</small><div className="timeline">{record.digests?.map((d:string,i:number)=><code key={d}>SOURCE {i+1} · {d.slice(0,18)}…</code>)}</div></section>}<footer>CivicSignal · source disagreement is a first-class result</footer></main>}
